export const SPV_PAGE_DATA = {
  summary: [
    {
      title: 'Total SPVs',
      value: 24,
      icon: 'solar:buildings-3-bold',
      iconColor: 'primary.main',
      iconBg: 'primary.lighter',
    },
    {
      title: 'Live Issuances',
      value: 12,
      icon: 'solar:chart-square-bold',
      iconColor: 'success.main',
      iconBg: 'success.lighter',
    },
    {
      title: 'AUM Managed',
      value: '486 Cr',
      icon: 'solar:wallet-money-bold',
      iconColor: 'warning.dark',
      iconBg: 'warning.lighter',
    },
    {
      title: 'Maturing Soon',
      value: 5,
      icon: 'solar:alarm-bold',
      iconColor: 'error.main',
      iconBg: 'error.lighter',
    },
  ],
  list: [
    {
      id: 'SPV-001',
      name: 'Smile Wave SPV-1',
      issuer: 'Funds Under Management',
      trustee: 'Catalyst Trusteeship',
      category: 'Receivables',
      stage: 'Live',
      status: 'Active',
      activePTC: 18,
      outstandingValue: 120,
      coupon: '11.8%',
      maturityDate: '2026-09-30',
      registrationNumber: 'SPV-MH-2025-001',
      incorporatedOn: 'Jan 15, 2025',
      monitoringTrustee: 'IDBI Trusteeship Services Ltd.',
      overviewFinancialSummary: {
        totalFum: '450 Cr',
        activeDeployment: '425 Cr',
        reserveFund: '25 Cr',
        investors: 28,
      },
      summaryCards: [
        { title: 'Funds Under Management', value: 'INR 450 Cr', icon: 'solar:chart-square-bold' },
        { title: 'Active PTCs', value: 18, icon: 'solar:document-text-bold' },
        { title: 'Total Pools', value: 3, icon: 'solar:buildings-3-bold' },
        { title: 'Active Investors', value: 28, icon: 'solar:users-group-rounded-bold' },
      ],
      poolPtc: [
        {
          id: 'POOL-001',
          name: 'Retail Pool - D1 Category',
          subtitle: 'D1 Receivables',
          status: 'Active',
          poolValue: 'INR 2 Cr',
          ptcsIssued: 5,
          merchants: 45,
        },
        {
          id: 'POOL-002',
          name: 'Corporate Pool - D0 Category',
          subtitle: 'D0 Receivables',
          status: 'Active',
          poolValue: 'INR 2 Cr',
          ptcsIssued: 4,
          merchants: 28,
        },
        {
          id: 'POOL-003',
          name: 'Mixed Pool - D1/D2 Category',
          subtitle: 'Mixed Receivables',
          status: 'Active',
          poolValue: 'INR 1 Cr',
          ptcsIssued: 3,
          merchants: 32,
        },
      ],
      ptcConversionSummary: [
        {
          series: 'SW-D1-2025-A1',
          issuedOn: 'Feb 28, 2026',
          amount: 'INR 500 Cr',
          maturity: 'May 28, 2026',
          investors: 8,
          status: 'Active',
          yieldValue: '12.5% Yield',
        },
        {
          series: 'SW-D1-2025-A2',
          issuedOn: 'Feb 25, 2026',
          amount: 'INR 650 Cr',
          maturity: 'Jun 25, 2026',
          investors: 10,
          status: 'Active',
          yieldValue: '12.8% Yield',
        },
        {
          series: 'SW-D0-2025-B1',
          issuedOn: 'Feb 20, 2026',
          amount: 'INR 420 Cr',
          maturity: 'Apr 20, 2026',
          investors: 6,
          status: 'Active',
          yieldValue: '11.9% Yield',
        },
        {
          series: 'SW-D1-2025-A3',
          issuedOn: 'Feb 18, 2026',
          amount: 'INR 380 Cr',
          maturity: 'Jun 18, 2026',
          investors: 7,
          status: 'Active',
          yieldValue: '13.0% Yield',
        },
      ],
      escrowAccount: {
        bankName: 'Yes Bank Ltd. - SPV Escrow',
        accountLabel: 'Escrow Account',
        accountNumber: 'YESB0SPV0001234567',
        ifscCode: 'YESB0000SPV',
        currentBalance: '450 Cr',
        branch: 'Lower Parel, Mumbai',
        accountType: 'Escrow - SPV Dedicated',
        openedOn: 'Jan 15, 2025',
        status: 'Active',
        note: 'This escrow account is exclusively managed by SPV-1 and receives investor funds for pool deployment.',
        summary: [
          { label: "Today's Inflow", value: 'INR 12.5 Cr' },
          { label: "Today's Outflow", value: 'INR 8.3 Cr' },
          { label: 'Pending Transactions', value: '5' },
        ],
        recentTransactions: [
          {
            id: 'ESC-TXN-5678',
            counterparty: 'From: Investor Escrow - INV-045',
            amount: 'INR 500.00 Cr',
            date: 'Mar 9, 2026',
            time: '10:30:00',
            utr: 'YES2026030900567',
            type: 'Inflow',
          },
          {
            id: 'ESC-TXN-5677',
            counterparty: 'To: Pool Deployment',
            amount: 'INR 320.00 Cr',
            date: 'Mar 9, 2026',
            time: '09:15:00',
            utr: 'YES2026030900566',
            type: 'Outflow',
          },
          {
            id: 'ESC-TXN-5676',
            counterparty: 'From: Investor Escrow - INV-032',
            amount: 'INR 750.00 Cr',
            date: 'Mar 8, 2026',
            time: '14:45:00',
            utr: 'YES2026030800565',
            type: 'Inflow',
          },
        ],
      },
      transactionHistory: [
        {
          id: 'TXN-SPV-8901',
          title: 'Aditya Mehta - PTC Purchase',
          subtitle: 'Aditya Mehta - PTC Purchase',
          amount: 'INR 500.00 Cr',
          pool: 'Retail Pool - D1',
          date: 'Mar 9, 2026',
          status: 'Processing',
        },
        {
          id: 'TXN-SPV-8900',
          title: 'Priya Sharma - Interest Payout',
          subtitle: 'Priya Sharma - Interest Payout',
          amount: 'INR 320.00 Cr',
          pool: 'Corporate Pool - D0',
          date: 'Mar 9, 2026',
          status: 'Completed',
        },
        {
          id: 'TXN-SPV-8899',
          title: 'Rajesh Kumar - PTC Purchase',
          subtitle: 'Rajesh Kumar - PTC Purchase',
          amount: 'INR 750.00 Cr',
          pool: 'Mixed Pool - D1/D2',
          date: 'Mar 8, 2026',
          status: 'Completed',
        },
      ],
      closedTransactions: [
        {
          id: 'TXN-SPV-8750',
          title: 'Vikram Singh - PTC Maturity Payout',
          subtitle: 'Vikram Singh - PTC Maturity Payout',
          amount: 'INR 450.00 Cr',
          pool: 'Retail Pool - D1',
          closedOn: 'Mar 1, 2026',
          status: 'Settled',
        },
        {
          id: 'TXN-SPV-8720',
          title: 'Neha Gupta - PTC Maturity Payout',
          subtitle: 'Neha Gupta - PTC Maturity Payout',
          amount: 'INR 600.00 Cr',
          pool: 'Corporate Pool - D0',
          closedOn: 'Feb 28, 2026',
          status: 'Settled',
        },
        {
          id: 'TXN-SPV-8690',
          title: 'Amit Patel - Early Redemption',
          subtitle: 'Amit Patel - Early Redemption',
          amount: 'INR 380.00 Cr',
          pool: 'Mixed Pool - D1/D2',
          closedOn: 'Feb 25, 2026',
          status: 'Settled',
        },
      ],
    },
    {
      id: 'SPV-002',
      name: 'Smile Wave SPV-2',
      issuer: 'Funds Under Management',
      trustee: 'Vistra ITCL',
      category: 'Gold Loans',
      stage: 'Funding',
      status: 'Pending',
      activePTC: 9,
      outstandingValue: 86,
      coupon: '12.4%',
      maturityDate: '2026-11-15',
      registrationNumber: 'SPV-MH-2025-002',
      incorporatedOn: 'Feb 08, 2025',
      monitoringTrustee: 'Vistra ITCL (India) Ltd.',
      overviewFinancialSummary: {
        totalFum: '310 Cr',
        activeDeployment: '280 Cr',
        reserveFund: '30 Cr',
        investors: 19,
      },
      summaryCards: [
        { title: 'Funds Under Management', value: 'INR 310 Cr', icon: 'solar:chart-square-bold' },
        { title: 'Active PTCs', value: 9, icon: 'solar:document-text-bold' },
        { title: 'Total Pools', value: 2, icon: 'solar:buildings-3-bold' },
        { title: 'Active Investors', value: 19, icon: 'solar:users-group-rounded-bold' },
      ],
      poolPtc: [
        {
          id: 'POOL-101',
          name: 'Gold Pool - D0 Category',
          subtitle: 'D0 Receivables',
          status: 'Active',
          poolValue: 'INR 1.6 Cr',
          ptcsIssued: 4,
          merchants: 22,
        },
        {
          id: 'POOL-102',
          name: 'Gold Pool - D1 Category',
          subtitle: 'D1 Receivables',
          status: 'Pending',
          poolValue: 'INR 0.9 Cr',
          ptcsIssued: 2,
          merchants: 14,
        },
      ],
      ptcConversionSummary: [
        {
          series: 'GL-D0-2025-A1',
          issuedOn: 'Feb 24, 2026',
          amount: 'INR 210 Cr',
          maturity: 'May 24, 2026',
          investors: 5,
          status: 'Active',
          yieldValue: '12.2% Yield',
        },
        {
          series: 'GL-D1-2025-A2',
          issuedOn: 'Feb 21, 2026',
          amount: 'INR 145 Cr',
          maturity: 'Jun 21, 2026',
          investors: 4,
          status: 'Pending',
          yieldValue: '12.9% Yield',
        },
      ],
      escrowAccount: {
        bankName: 'HDFC Bank Ltd. - SPV Escrow',
        accountLabel: 'Escrow Account',
        accountNumber: 'HDFC0SPV0002234568',
        ifscCode: 'HDFC0000SPV',
        currentBalance: '310 Cr',
        branch: 'BKC, Mumbai',
        accountType: 'Escrow - SPV Dedicated',
        openedOn: 'Feb 08, 2025',
        status: 'Active',
        note: 'This escrow account is maintained for SPV-2 collections, drawdowns, and structured investor payouts.',
        summary: [
          { label: "Today's Inflow", value: 'INR 9.1 Cr' },
          { label: "Today's Outflow", value: 'INR 6.4 Cr' },
          { label: 'Pending Transactions', value: '3' },
        ],
        recentTransactions: [
          {
            id: 'ESC-TXN-5721',
            counterparty: 'From: Investor Escrow - INV-018',
            amount: 'INR 220.00 Cr',
            date: 'Mar 9, 2026',
            time: '11:20:00',
            utr: 'HDF2026030900721',
            type: 'Inflow',
          },
          {
            id: 'ESC-TXN-5720',
            counterparty: 'To: Gold Loan Pool Funding',
            amount: 'INR 145.00 Cr',
            date: 'Mar 9, 2026',
            time: '10:05:00',
            utr: 'HDF2026030900720',
            type: 'Outflow',
          },
          {
            id: 'ESC-TXN-5719',
            counterparty: 'To: Trustee Reserve Transfer',
            amount: 'INR 18.00 Cr',
            date: 'Mar 8, 2026',
            time: '16:10:00',
            utr: 'HDF2026030800719',
            type: 'Outflow',
          },
        ],
      },
      transactionHistory: [
        {
          id: 'TXN-SPV-8912',
          title: 'Nihar Shah - Gold Pool Buy-in',
          subtitle: 'Nihar Shah - Gold Pool Buy-in',
          amount: 'INR 210.00 Cr',
          pool: 'Gold Pool - D0',
          date: 'Mar 9, 2026',
          status: 'Processing',
        },
        {
          id: 'TXN-SPV-8911',
          title: 'Reserve Account Funding',
          subtitle: 'Reserve Account Funding',
          amount: 'INR 18.00 Cr',
          pool: 'Gold Pool - Reserve',
          date: 'Mar 8, 2026',
          status: 'Completed',
        },
        {
          id: 'TXN-SPV-8910',
          title: 'Anita Desai - Coupon Payout',
          subtitle: 'Anita Desai - Coupon Payout',
          amount: 'INR 42.00 Cr',
          pool: 'Gold Pool - D1',
          date: 'Mar 8, 2026',
          status: 'Pending',
        },
      ],
      closedTransactions: [
        {
          id: 'TXN-SPV-8708',
          title: 'Karan Malhotra - Gold Pool Maturity',
          subtitle: 'Karan Malhotra - Gold Pool Maturity',
          amount: 'INR 240.00 Cr',
          pool: 'Gold Pool - D0',
          closedOn: 'Mar 1, 2026',
          status: 'Settled',
        },
        {
          id: 'TXN-SPV-8707',
          title: 'Reserve Redemption Transfer',
          subtitle: 'Reserve Redemption Transfer',
          amount: 'INR 75.00 Cr',
          pool: 'Gold Pool - Reserve',
          closedOn: 'Feb 27, 2026',
          status: 'Settled',
        },
      ],
    },
    {
      id: 'SPV-003',
      name: 'Smile Wave SPV-3',
      issuer: 'Funds Under Management',
      trustee: 'Beacon Trusteeship',
      category: 'MSME',
      stage: 'Monitoring',
      status: 'Active',
      activePTC: 24,
      outstandingValue: 142,
      coupon: '13.1%',
      maturityDate: '2026-06-20',
      registrationNumber: 'SPV-MH-2025-003',
      incorporatedOn: 'Mar 20, 2025',
      monitoringTrustee: 'Beacon Trusteeship Ltd.',
      overviewFinancialSummary: {
        totalFum: '520 Cr',
        activeDeployment: '471 Cr',
        reserveFund: '49 Cr',
        investors: 34,
      },
      summaryCards: [
        { title: 'Funds Under Management', value: 'INR 520 Cr', icon: 'solar:chart-square-bold' },
        { title: 'Active PTCs', value: 24, icon: 'solar:document-text-bold' },
        { title: 'Total Pools', value: 4, icon: 'solar:buildings-3-bold' },
        { title: 'Active Investors', value: 34, icon: 'solar:users-group-rounded-bold' },
      ],
      poolPtc: [
        {
          id: 'POOL-201',
          name: 'MSME Pool - D1 Category',
          subtitle: 'D1 Receivables',
          status: 'Active',
          poolValue: 'INR 2.4 Cr',
          ptcsIssued: 6,
          merchants: 38,
        },
        {
          id: 'POOL-202',
          name: 'MSME Pool - D2 Category',
          subtitle: 'D2 Receivables',
          status: 'Active',
          poolValue: 'INR 1.8 Cr',
          ptcsIssued: 5,
          merchants: 29,
        },
        {
          id: 'POOL-203',
          name: 'MSME Mixed Pool',
          subtitle: 'Mixed Receivables',
          status: 'Active',
          poolValue: 'INR 1.2 Cr',
          ptcsIssued: 3,
          merchants: 17,
        },
      ],
      ptcConversionSummary: [
        {
          series: 'MS-D1-2025-A1',
          issuedOn: 'Feb 27, 2026',
          amount: 'INR 410 Cr',
          maturity: 'May 27, 2026',
          investors: 9,
          status: 'Active',
          yieldValue: '12.6% Yield',
        },
        {
          series: 'MS-D2-2025-B1',
          issuedOn: 'Feb 23, 2026',
          amount: 'INR 260 Cr',
          maturity: 'Jun 23, 2026',
          investors: 6,
          status: 'Active',
          yieldValue: '11.9% Yield',
        },
      ],
      escrowAccount: {
        bankName: 'ICICI Bank Ltd. - SPV Escrow',
        accountLabel: 'Escrow Account',
        accountNumber: 'ICIC0SPV0003234569',
        ifscCode: 'ICIC0000SPV',
        currentBalance: '520 Cr',
        branch: 'Fort, Mumbai',
        accountType: 'Escrow - SPV Dedicated',
        openedOn: 'Mar 20, 2025',
        status: 'Active',
        note: 'This escrow account is ring-fenced for SPV-3 and is used for investor inflows and monitored repayments.',
        summary: [
          { label: "Today's Inflow", value: 'INR 15.8 Cr' },
          { label: "Today's Outflow", value: 'INR 11.2 Cr' },
          { label: 'Pending Transactions', value: '7' },
        ],
        recentTransactions: [
          {
            id: 'ESC-TXN-5814',
            counterparty: 'From: Investor Escrow - INV-061',
            amount: 'INR 410.00 Cr',
            date: 'Mar 9, 2026',
            time: '12:40:00',
            utr: 'ICI2026030900814',
            type: 'Inflow',
          },
          {
            id: 'ESC-TXN-5813',
            counterparty: 'To: MSME Pool Drawdown',
            amount: 'INR 260.00 Cr',
            date: 'Mar 9, 2026',
            time: '09:40:00',
            utr: 'ICI2026030900813',
            type: 'Outflow',
          },
          {
            id: 'ESC-TXN-5812',
            counterparty: 'From: Collections Sweep - MSME',
            amount: 'INR 88.00 Cr',
            date: 'Mar 8, 2026',
            time: '17:25:00',
            utr: 'ICI2026030800812',
            type: 'Inflow',
          },
        ],
      },
      transactionHistory: [
        {
          id: 'TXN-SPV-8925',
          title: 'Collections Sweep - MSME North',
          subtitle: 'Collections Sweep - MSME North',
          amount: 'INR 88.00 Cr',
          pool: 'MSME Pool - D2',
          date: 'Mar 9, 2026',
          status: 'Completed',
        },
        {
          id: 'TXN-SPV-8924',
          title: 'Rohit Jain - Investor Allocation',
          subtitle: 'Rohit Jain - Investor Allocation',
          amount: 'INR 310.00 Cr',
          pool: 'MSME Pool - D1',
          date: 'Mar 9, 2026',
          status: 'Processing',
        },
        {
          id: 'TXN-SPV-8923',
          title: 'Interest Distribution - Series B1',
          subtitle: 'Interest Distribution - Series B1',
          amount: 'INR 57.00 Cr',
          pool: 'MSME Pool - Income',
          date: 'Mar 8, 2026',
          status: 'Completed',
        },
      ],
      closedTransactions: [
        {
          id: 'TXN-SPV-8688',
          title: 'MSME Series B Maturity',
          subtitle: 'MSME Series B Maturity',
          amount: 'INR 290.00 Cr',
          pool: 'MSME Pool - D2',
          closedOn: 'Mar 2, 2026',
          status: 'Settled',
        },
        {
          id: 'TXN-SPV-8687',
          title: 'Investor Exit - Series A',
          subtitle: 'Investor Exit - Series A',
          amount: 'INR 130.00 Cr',
          pool: 'MSME Pool - D1',
          closedOn: 'Feb 26, 2026',
          status: 'Settled',
        },
      ],
    },
    {
      id: 'SPV-004',
      name: 'Smile Wave SPV-4',
      issuer: 'Funds Under Management',
      trustee: 'Catalyst Trusteeship',
      category: 'Consumer Loans',
      stage: 'Closed',
      status: 'Closed',
      activePTC: 14,
      outstandingValue: 58,
      coupon: '10.9%',
      maturityDate: '2026-04-05',
      registrationNumber: 'SPV-MH-2025-004',
      incorporatedOn: 'Apr 12, 2025',
      monitoringTrustee: 'Catalyst Trusteeship Ltd.',
      overviewFinancialSummary: {
        totalFum: '190 Cr',
        activeDeployment: '175 Cr',
        reserveFund: '15 Cr',
        investors: 16,
      },
      summaryCards: [
        { title: 'Funds Under Management', value: 'INR 190 Cr', icon: 'solar:chart-square-bold' },
        { title: 'Active PTCs', value: 14, icon: 'solar:document-text-bold' },
        { title: 'Total Pools', value: 2, icon: 'solar:buildings-3-bold' },
        { title: 'Active Investors', value: 16, icon: 'solar:users-group-rounded-bold' },
      ],
      poolPtc: [
        {
          id: 'POOL-301',
          name: 'Consumer Pool - Closure Category',
          subtitle: 'Closed Receivables',
          status: 'Closed',
          poolValue: 'INR 0.8 Cr',
          ptcsIssued: 2,
          merchants: 9,
        },
      ],
      ptcConversionSummary: [
        {
          series: 'CN-CL-2025-Z1',
          issuedOn: 'Feb 10, 2026',
          amount: 'INR 95 Cr',
          maturity: 'Apr 10, 2026',
          investors: 3,
          status: 'Closed',
          yieldValue: '10.8% Yield',
        },
      ],
      escrowAccount: {
        bankName: 'Axis Bank Ltd. - SPV Escrow',
        accountLabel: 'Escrow Account',
        accountNumber: 'UTIB0SPV0004234570',
        ifscCode: 'UTIB0000SPV',
        currentBalance: '190 Cr',
        branch: 'Nariman Point, Mumbai',
        accountType: 'Escrow - SPV Dedicated',
        openedOn: 'Apr 12, 2025',
        status: 'Closed',
        note: 'This escrow account was dedicated to SPV-4 and is retained only for closure reconciliations and audit references.',
        summary: [
          { label: "Today's Inflow", value: 'INR 2.4 Cr' },
          { label: "Today's Outflow", value: 'INR 4.1 Cr' },
          { label: 'Pending Transactions', value: '1' },
        ],
        recentTransactions: [
          {
            id: 'ESC-TXN-5902',
            counterparty: 'From: Final Collections Sweep',
            amount: 'INR 14.00 Cr',
            date: 'Mar 8, 2026',
            time: '13:10:00',
            utr: 'UTI2026030800902',
            type: 'Inflow',
          },
          {
            id: 'ESC-TXN-5901',
            counterparty: 'To: Closure Reconciliation',
            amount: 'INR 21.00 Cr',
            date: 'Mar 8, 2026',
            time: '11:45:00',
            utr: 'UTI2026030800901',
            type: 'Outflow',
          },
        ],
      },
      transactionHistory: [
        {
          id: 'TXN-SPV-8934',
          title: 'Final Coupon Payout',
          subtitle: 'Final Coupon Payout',
          amount: 'INR 21.00 Cr',
          pool: 'Consumer Pool - Closure',
          date: 'Mar 8, 2026',
          status: 'Completed',
        },
        {
          id: 'TXN-SPV-8933',
          title: 'Residual Collections Sweep',
          subtitle: 'Residual Collections Sweep',
          amount: 'INR 14.00 Cr',
          pool: 'Consumer Pool - Residual',
          date: 'Mar 8, 2026',
          status: 'Completed',
        },
      ],
      closedTransactions: [
        {
          id: 'TXN-SPV-8655',
          title: 'Consumer Pool Final Settlement',
          subtitle: 'Consumer Pool Final Settlement',
          amount: 'INR 95.00 Cr',
          pool: 'Consumer Pool - Closure',
          closedOn: 'Feb 24, 2026',
          status: 'Settled',
        },
      ],
    },
  ],
  poolBuilder: {
    title: 'Pool Builder',
    sectionTitle: 'Haircut Configuration',
    steps: [
      { id: 1, label: 'Select Merchants', state: 'done' },
      { id: 2, label: 'Select Receivables', state: 'done' },
      { id: 3, label: 'Apply Haircut', state: 'active' },
      { id: 4, label: 'Add Enhancement', state: 'idle' },
      { id: 5, label: 'Create PTC', state: 'idle' },
    ],
    haircuts: [
      { label: 'D0 Receivables', value: '5%', amount: 'INR 45 Cr' },
      { label: 'D1 Receivables', value: '8%', amount: 'INR 85 Cr' },
      { label: 'D2 Receivables', value: '12%', amount: 'INR 32 Cr' },
    ],
  },
  recentPTCIssuances: {
    title: 'Recent PTC Issuances',
    items: [
      {
        id: 'PTC-001',
        series: 'SW-D1-2025-A1',
        amount: 'INR 50 Cr',
        tenor: '90 days',
        issuedOn: 'Feb 28, 2026',
        yield: '12.5%',
      },
      {
        id: 'PTC-002',
        series: 'SW-D1-2025-A2',
        amount: 'INR 65 Cr',
        tenor: '120 days',
        issuedOn: 'Feb 25, 2026',
        yield: '12.8%',
      },
      {
        id: 'PTC-003',
        series: 'SW-D2-2025-B1',
        amount: 'INR 42 Cr',
        tenor: '60 days',
        issuedOn: 'Feb 20, 2026',
        yield: '11.9%',
      },
    ],
  },
};

export const SPV_SUMMARY = SPV_PAGE_DATA.summary;
export const SPV_DATA = SPV_PAGE_DATA.list;
export const SPV_POOL_BUILDER = SPV_PAGE_DATA.poolBuilder;
export const SPV_RECENT_PTC_ISSUANCES = SPV_PAGE_DATA.recentPTCIssuances;
export const getSpvById = (id) => SPV_DATA.find((item) => item.id === id);
